hmcts/send-letter-client

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sendletter/SendLetterAutoConfiguration.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/SendLetterApi.java
- src/main/java/uk/gov/hmcts/reform/sendletter/healthcheck/SendLetterHealthApi.java
https://tools.hmcts.net/jira/browse/ROC-3536
Updating to Spring Boot 2 / Spring Framework 5.
> ROC-3636: Update to Spring Boot 2 / Spring Framework 5

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sendletter/api/LetterWithPdfsRequest.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/SendLetterApi.java
> upgraded api to support letter with pdfs

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sendletter/api/LetterWithPdfsRequest.java
- Added getter for document as it is required for deserialisation.
- Bumped version
```
[ ] Yes
[ x] No
```
> Add getter deserialization

- .travis.yml
- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/sendletter/AutoConfigurationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/sendletter/NoAutoConfigurationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/sendletter/TestApplication.java
- src/main/java/uk/gov/hmcts/reform/sendletter/CustomFeignErrorDecoder.java
- src/test/java/uk/gov/hmcts/reform/sendletter/CustomFeignErrorDecoderTest.java
- src/test/java/uk/gov/hmcts/reform/sendletter/healthcheck/SendLetterHealthIndicatorTest.java
Adding basic tests. Pretty much basics. Covering all possible scenarios without mocking up actual send letter api which would not make sense at all.
Read commit log if you want to please your inner git ref lover or just approve as it's mainly test package driven.
Would recommend just to double check `.travis.yml` - had to add testing tasks therefore did no want to keep unformatted version of it there. [Commit](https://github.com/hmcts/send-letter-client/commit/70741c86f1b3e34a8a6e699ecc2ffd44198726d7) is separate for formatting.
```
[ ] Yes
[x] No
```
> Tests :scream_cat:

- Jenkinsfile_nightly
Will check for any vulnerabilities as per usual services
```
[ ] Yes
[x] No
```
> Add Jenkinsfile for nightly builds

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
Preparing full upgrade and hope for nightly build cover the vulnerabilities for me. Or will run them myself after finishing all dependency review. Here:
- gradle
- plugins
- test implementation
```
[ ] Yes
[x] No
```
> Update dependencies excluding spring

- build.gradle
Follow up of #23. This expands to other dependencies but they are under the flag of spring dependency manager so kind of - valid
- Spring boot
- openfeign
- guava
- jackson-databind
```
[ ] Yes
[x] No
```
> Update the rest of dependencies

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sendletter/api/LetterWithPdfsRequest.java
Change string to byte for pdf request
```
[ ] Yes
[ ] No
```
> Change string to byte for pdf request

- .travis.yml
Since #22 tags not being picked up anymore. Including the semver regex to match the case
```
[ ] Yes
[x] No
```
> Allow tags to be built/released

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sendletter/api/SendLetterApi.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/model/v3/Document.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/model/v3/Letter.java
interestingly, this repo has no tests....
> Add v3 endpoint support

- build.gradle
- config/owasp/suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
- src/main/java/uk/gov/hmcts/reform/sendletter/healthcheck/SendLetterHealthApi.java
Migrating to spring boot 2.2. Includes incompatible content type header changes as previous version has become deprecated.
```
[ ] Yes
[x] No // not really that much of a breaking change
```
> Update dependencies: migrate to spring boot 2.2

- build.gradle
new owasp report (from Friday): https://nvd.nist.gov/vuln/detail/CVE-2020-9488
```
[ ] Yes
[x] No
```
> Fix logging vulnerability

- build.gradle
- config/owasp/suppressions.xml
avoid vulnerability
```
[ ] Yes
[x] No
```
> avoid vulnerability

- build.gradle
- config/owasp/suppressions.xml
Suppress vulnerability
```
[ ] Yes
[x] No
```
> Suppress vulnerability

- config/owasp/suppressions.xml
upgrade xmlns to support until
```
[ ] Yes
[x] No
```
> upgrade xmlns to support until

- build.gradle
- src/integrationTest/java/api/SendLetterApiTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/sendletter/api/SendLetterApiTest.java
https://tools.hmcts.net/jira/browse/DTSBP-15
Added integration test for SendLetterApiTest
```
[ ] Yes
[x ] No
```
> DTSBP-15: Added integration test for SendLetterApiTest

- Jenkinsfile_nightly
change product to rpe in line with send-letter-service to fix nightly tests
```
[ ] Yes
[x] No
```
> change product to rpe in line with send-letter-service

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/sendletter/AutoConfigurationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/sendletter/NoAutoConfigurationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/sendletter/api/ISendLetterApiTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/sendletter/api/proxy/SendLetterApiProxyTest.java
- src/main/java/uk/gov/hmcts/reform/sendletter/CustomFeignErrorDecoder.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/LetterStatus.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/SendLetterApi.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/config/RetryConfig.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/config/RetryPolicy.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/proxy/SendLetterApiProxy.java
- src/main/resources/META-INF/spring.factories
- src/test/java/uk/gov/hmcts/reform/sendletter/api/SendLetterApiTest.java
- src/test/java/uk/gov/hmcts/reform/sendletter/api/proxy/SendLetterApiProxyTest.java
https://tools.hmcts.net/jira/browse/DTSBP-84
Updates to support async db insert
```
[ ] Yes
[x ] No
```
> DTSBP-84: Updates for async db insert

- src/main/java/uk/gov/hmcts/reform/sendletter/api/config/RetryConfig.java
https://tools.hmcts.net/jira/browse/DTSBPS-11
Removed unused import
```
[ ] Yes
[ ] No
```
> DTSBP-84: Removed unused import

- build.gradle
- src/main/java/uk/gov/hmcts/reform/sendletter/api/config/RetryConfig.java
https://tools.hmcts.net/jira/browse/DTSBPS-11
Incremented release version
```
[ ] Yes
[ ] No
```
> Dtsbp 84 v1

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/sendletter/api/config/RetryConfig.java
> Update SpringBoot to fix some CVEs

- src/integrationTest/java/uk/gov/hmcts/reform/sendletter/api/ISendLetterApiTest.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/SendLetterApi.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/proxy/SendLetterApiProxy.java
- src/test/java/uk/gov/hmcts/reform/sendletter/api/SendLetterApiTest.java
https://tools.hmcts.net/jira/browse/DTSBPS-109
To handle async duplicate Letter. 
```
[ ] Yes
[ x] No
```
> DTSBP-109: Rejecting duplicate print requests

- build.gradle
https://tools.hmcts.net/jira/browse/DTSBPS-109
Updated build version
```
[ ] Yes
[x ] No
```
> DTSBP-109: Updating build number

- build.gradle
> reverted  com.github.ben-manes.versions from 0.38.0 to 0.36.0

- build.gradle
> downgrade io.github.openfeign 11.1 to 11.0

- build.gradle
Build is breaking with version .0.38.0
```
[ ] Yes
[X ] No
```
> downgrade ben-manes 0.38.0 to 0.36.0

- .github/workflows/gradle.yml
- .github/workflows/jitpack-build.yml
- build.gradle
- jitpack.yml
- Remove bintray configuration 
- Remove bintrayUpload task
- Add jitpack workflow
- Add jitpack configuration to use Java 11
> DTSPO-1792 - Add JitPack build workflow

- build.gradle
DTSBPS-626
spring-vulnerabilities
```
[ ] Yes
[x] No
```
> DTSBPS-626: spring-vulnerabilities

- src/main/java/uk/gov/hmcts/reform/sendletter/api/proxy/SendLetterApiProxy.java
https://tools.hmcts.net/jira/browse/DTSBPS-434
deprecated old end point
```
[ ] Yes
[ x] No
```
> DTSBPS-434: deprecated old end point

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
DTSBPS-643
spring boot upgrade
```
[ ] Yes
[x] No
```
> DTSBPS-643: spring boot upgrade

- build.gradle
DTSBPS-643
Removed used jar dependency
```
[ ] Yes
[ x] No
```
> DTSBPS-643: Release version

- README.md
Remove old badge and added recently in-use badge
```
[ ] Yes
[x] No
```
> Added jitpack badge

- build.gradle
> Bump owasp version

- config/owasp/suppressions.xml
> Suppressed vulnerabilities

- .github/workflows/gradle.yml
- build.gradle
https://tools.hmcts.net/jira/browse/DTSBPS-1309
Reverting Java 17 upgrade as all services are not on java17 
```
[ ] Yes
[x] No
```
> DTSBPS-1309: Revert Java 17 upgrade

- src/main/java/uk/gov/hmcts/reform/sendletter/api/config/RetryConfig.java
> amending retry limit and backoff time

- .github/workflows/gradle.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/FACT-1563
Monthly updates spotted by renovate.
```
[ ] Yes
[x] No
```
> FACT-1563 Monthly Updates

- src/main/java/uk/gov/hmcts/reform/sendletter/CustomFeignErrorDecoder.java
- src/main/java/uk/gov/hmcts/reform/sendletter/SendLetterAutoConfiguration.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/Document.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/Letter.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/LetterStatus.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/LetterWithPdfsRequest.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/SendLetterApi.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/SendLetterResponse.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/config/RetryConfig.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/config/RetryPolicy.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/exception/ClientHttpErrorException.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/exception/ServerHttpErrorException.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/model/v3/Document.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/model/v3/LetterV3.java
- src/main/java/uk/gov/hmcts/reform/sendletter/api/proxy/SendLetterApiProxy.java
- src/main/java/uk/gov/hmcts/reform/sendletter/healthcheck/InternalHealth.java
- src/main/java/uk/gov/hmcts/reform/sendletter/healthcheck/SendLetterHealthApi.java
- src/main/java/uk/gov/hmcts/reform/sendletter/healthcheck/SendLetterHealthIndicator.java
https://tools.hmcts.net/jira/browse/FACT-1470
added docstrings to send letter client
```
[ ] Yes
[x] No
```
> FACT-1470 added docstrings to send-letter-client

- .github/workflows/gradle.yml
- .gitignore
- build.gradle
- jitpack.yml
https://tools.hmcts.net/jira/browse/FACT-1843
update from 17 to 21
```
[ ] Yes
[ ] No
```
> FACT-1843 J21 changes

- build.gradle
https://tools.hmcts.net/jira/browse/FACT-1906
update send letter client dependancies
```
[ ] Yes
[x] No
```
> FACT-1906 update dependancies

- README.md
> FACT-1906_2 poke

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/FACT-1981
- Dependency Updates
Major Version Jumps
- Owasp Dependency Check
```
[ ] Yes
[x] No
```
> FACT-1981 - CVE and Dependency Updates

- build.gradle
> FACT-2386 dependancy updates

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/FACT-2409
Updates
```
[ ] Yes
[x] No
```
> FACT-2409 dependency updates

- .github/renovate.json
> FACT-2429 renovate changes
